def create_tables(cur) :
    mycursor=cur.cursor()
    mycursor.execute("CREATE TABLE MOVIE_INFO(ID INT PRIMARY KEY, TITLE VARCHAR(500))")
    mycursor.execute("CREATE TABLE MOVIE_POPULARITY(M_ID INT PRIMARY KEY, VOTE_AVG DECIMAL(5,3), VOTE_COUNT INT, POPULARITY DECIMAL(15,3), RUNTIME INT, FOREIGN KEY(M_ID) REFERENCES MOVIE_INFO(ID))")
    mycursor.execute("CREATE TABLE MOVIE_STATUS(M_ID INT PRIMARY KEY, STATUS VARCHAR(50), RELEASE_DATE DATE, FOREIGN KEY(M_ID) REFERENCES MOVIE_INFO(ID))")
    mycursor.execute("CREATE TABLE MOVIE_CATEGORY (M_ID INT PRIMARY KEY, ADULT VARCHAR(10), ORIGINAL_LANG VARCHAR(30), FOREIGN KEY(M_ID) REFERENCES MOVIE_INFO(ID))")
    mycursor.execute("CREATE TABLE MOVIE_GENRE (M_ID INT , GENRE VARCHAR(30), PRIMARY KEY(M_ID, GENRE), FOREIGN KEY(M_ID) REFERENCES MOVIE_INFO(ID))")
    mycursor.execute("CREATE TABLE MOVIE_SPOKEN_LANG (M_ID INT, SP_LANG VARCHAR(30), PRIMARY KEY(M_ID, SP_LANG), FOREIGN KEY(M_ID) REFERENCES MOVIE_INFO(ID))")
    mycursor.execute("CREATE TABLE MOVIE_ECONOMICS (M_ID INT PRIMARY KEY, BUDGET BIGINT, REVENUE BIGINT, FOREIGN KEY(M_ID) REFERENCES MOVIE_INFO(ID))")
